### ISSUE TITLE
[bug] Notification timing parameter not working as expected in 

### ISSUE THREAD

**Issue by nicxes** [manups4e/ScaleformUI#118]
I've been using the ScaleformUI.Notifications:ShowHelpNotification function in my project, and overall it works well. However, I've noticed that the last parameter, which is supposed to set the duration of the notification, doesn't seem to work correctly.

Specifically, when I pass in a value of 200000 milliseconds, as in `ScaleformUI.Notifications:ShowHelpNotification('TEXT', 200000)` the notification does display for a while, but it never stays on the screen for the full duration. In fact, it seems like the maximum duration it ever shows for is around 5000 milliseconds.

I've tried different values for the timing parameter, but the behavior is always the same: the notification disappears much earlier than expected.

**Comment by manups4e** [comment]
Notification time can't be more than 5000ms because R* decided so, even using 20000 R* natives will max it to 5000.. in this case i suggest you to not input the duration parameter, that will show the notification for 1 frame.. you can loop it into a thread for 20seconds.. definitely not a bug. Sorry
